:: Generated by: https://github.com/openapitools/openapi-generator.git
::

@echo off

if not exist ".\nuget.exe" powershell -Command "(new-object System.Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', '.\nuget.exe')"
.\nuget.exe install src\Zuora\packages.config -o packages

if not exist ".\bin" mkdir bin

copy packages\Newtonsoft.Json.13.0.3\lib\net6.0\Newtonsoft.Json.dll bin\Newtonsoft.Json.dll
copy packages\JsonSubTypes.2.0.1\lib\netstandard2.0\JsonSubTypes.dll bin\JsonSubTypes.dll
copy packages\RestSharp.106.15.0\lib\netstandard2.0\RestSharp.dll bin\RestSharp.dll
%CSCPATH%\csc  /reference:bin\Newtonsoft.Json.dll;bin\JsonSubTypes.dll;bin\RestSharp.dll;System.ComponentModel.DataAnnotations.dll  /target:library /out:bin\Zuora.dll /recurse:src\Zuora\*.cs /doc:bin\Zuora.xml
